--[[ AMETHYST --------------------------------------------------------------------------------------

@package     Amethyst
@author      Richard & Nymphie
@build       v1.4.0
@release     03.27.2017
@owner       76561198075351542

BY MODIFYING THIS FILE -- YOU UNDERSTAND THAT THE ABOVE MENTIONED AUTHORS CANNOT BE HELD RESPONSIBLE
FOR ANY ISSUES THAT ARISE. AS A CUSTOMER TO THE ORIGINAL PURCHASED COPY OF THIS SCRIPT, YOU ARE
ENTITLED TO STANDARD SUPPORT WHICH CAN BE PROVIDED USING [SCRIPTFODDER.COM]. ONLY THE ORIGINAL
PURCHASER OF THIS SCRIPT CAN RECEIVE SUPPORT.

--------------------------------------------------------------------------------------------------]]

Amethyst = Amethyst or {}

--[[ AMETHYST --------------------------------------------------------------------------------------

FAILSAFE THEME

Do NOT modify the values below under ANY circumstances. If you want to edit the theme, you need to
go into /sh/themes/ and modify the correct one. These values are a failsafe so that if a theme is
missing values, it will load defaults so you don't error out. This is your only warning. If you do
modify these and I see that they have been -- you will get NO SUPPORT.

--------------------------------------------------------------------------------------------------]]

Amethyst.Theme["failsafe"] =
{
    {
        DataSort = 0,
        DataID = "amethyst_category_compactmode",
        DataName = "Compat Mode",
        DataType = "category",
    },
    {
        DataSort = 10,
        DataID = "amethyst_desc_compactmode",
        DataName = "Settings in this section are for the general layout of the F4 menu. If you are having frame issues, it is advised that you disable any graphical enhancements such as dimming or the bokeh effect.",
        DataType = "desc",
    },
    {
        DataSort = 20,
        DataID = "amethyst_m_compactmode_enabled",
        DataName = "Compact Mode Enabled",
        DataDesc = "Gets rid of a few non-essentials within the F4 menu (usually good for more FPS).",
        DataType = "checkbox",
        DataDefault = 0,
    },
    {
        DataSort = 30,
        DataID = "amethyst_m_compactmode_showheader_enabled",
        DataName = "Show Header About Menu",
        DataDesc = "Show the header above the nav menu (the panel with the network name, ticker, icons, etc.)",
        DataType = "checkbox",
        DataDefault = 1,
    },
    {
        DataSort = 40,
        DataID = "amethyst_m_compactmode_textwbuttons_enabled",
        DataName = "Menu Text and Icons",
        DataDesc = "Enabled displays icons to the left of the menu text. Disabled shows icons only.",
        DataType = "checkbox",
        DataDefault = 0,
    },
    {
        DataSort = 50,
        DataID = "amethyst_m_compactmode_menu_bcolor",
        DataName = "Nav Menu BG Color",
        DataDesc = "Color of the navigational menu background.",
        DataType = "rgba",
        DataValues = { red = 10, alpha = 200, blue = 10, green = 10},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 60,
        DataID = "amethyst_m_compactmode_menu_icolor",
        DataName = "Nav Menu Icon Color",
        DataDesc = "Color of the icons within navigational menu.",
        DataType = "rgba",
        DataValues = { red = 255, alpha = 255, blue = 255, green = 255},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 70,
        DataID = "amethyst_m_compactmode_menu_tcolor",
        DataName = "Nav Menu Text Color",
        DataDesc = "Color of text within navigational menu.",
        DataType = "rgba",
        DataValues = { red = 255, alpha = 255, blue = 255, green = 255},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 80,
        DataID = "amethyst_m_compactmode_menu_ucolor",
        DataName = "Nav Menu Selection Color",
        DataDesc = "Color of the bar under a nav item that is hovered/selected.",
        DataType = "rgba",
        DataValues = { red = 255, alpha = 255, blue = 255, green = 255},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 90,
        DataID = "amethyst_m_compactmode_menu_bspacing",
        DataName = "Button Spacing",
        DataDesc = "The spacing between each button (right-side).",
        DataType = "slider",
        DataDefault = 5,
        DataValues = {  },
        DataMin = 0,
        DataMax = 15,
    },
    {
        DataSort = 100,
        DataID = "amethyst_padding_compactmode",
        DataName = "Padding",
        DataType = "padding",
    },
    {
        DataSort = 110,
        DataID = "amethyst_category_general",
        DataName = "General",
        DataType = "category",
    },
    {
        DataSort = 120,
        DataID = "amethyst_desc_general",
        DataName = "Settings in this section are for the general layout of the F4 menu. If you are having frame issues, it is advised that you disable any graphical enhancements such as dimming or the bokeh effect.",
        DataType = "desc",
    },
    {
        DataSort = 135,
        DataID = "amethyst_m_grid_background_enabled",
        DataName = "Grid Background Enabled",
        DataDesc = "Display grid lines for certain menu items.",
        DataType = "checkbox",
        DataDefault = 0,
    },
    {
        DataSort = 140,
        DataID = "amethyst_m_clock_enabled",
        DataName = "Clock Enabled",
        DataDesc = "Display the clock to the top left -- (Compact-Mode must be disabled to show clock).",
        DataType = "checkbox",
        DataDefault = 1,
    },
    {
        DataSort = 150,
        DataID = "amethyst_m_dim_enabled",
        DataName = "Dim Wallpaper",
        DataDesc = "Dim the background when you activate the F4 menu.",
        DataType = "checkbox",
        DataDefault = 1,
    },
    {
        DataSort = 160,
        DataID = "amethyst_m_background_style",
        DataName = "Background Style",
        DataDesc = "Choose what types of backgrounds to use",
        DataType = "dropdown",
        DataDefault = "None",
        DataValues = {"None", "Live", "Images"},
    },
    {
        DataSort = 170,
        DataID = "amethyst_m_bokeh_fx_enabled",
        DataName = "Bokeh FX Enabled",
        DataDesc = "Display a bokeh FX in your background",
        DataType = "checkbox",
        DataDefault = 1,
    },
    {
        DataSort = 180,
        DataID = "amethyst_m_bokeh_style_enabled",
        DataName = "Bokeh Style",
        DataDesc = "Display a bokeh FX in your background",
        DataType = "dropdown",
        DataDefault = "circles",
        DataValues = {"circles", "gradients", "outlines"},
    },
    {
        DataSort = 181,
        DataIsVisible = true,
        DataID = "amethyst_m_bokeh_multiplier",
        DataName = "Bokeh Multiplier",
        DataDesc = "Multiplier amount for bokeh circles.",
        DataType = "slider",
        DataDefault = 25,
        DataValues = {  },
        DataMin = 0,
        DataMax = 100,
    },
    {
        DataSort = 190,
        DataID = "amethyst_m_bokeh_alpha",
        DataName = "Bokeh Alpha",
        DataDesc = "Opacity amount for bokeh circles.",
        DataType = "slider",
        DataDefault = 10,
        DataValues = {  },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 200,
        DataID = "amethyst_m_outsideborder_thickness",
        DataName = "Outside Border Thickness",
        DataDesc = "How think should the outside border be?",
        DataType = "slider",
        DataDefault = 2,
        DataValues = {  },
        DataMin = 0,
        DataMax = 10,
    },
    {
        DataSort = 210,
        DataID = "amethyst_m_outsideborder_color",
        DataName = "Outside Border Color",
        DataDesc = "Outside border colors.",
        DataType = "rgba",
        DataValues = { red = 255, alpha = 3, blue = 255, green = 255},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 220,
        DataID = "amethyst_m_dcolor",
        DataName = "Dim Color",
        DataDesc = "Color to use for dimming the background.",
        DataType = "rgba",
        DataValues = { red = 15, alpha = 200, blue = 15, green = 15},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 230,
        DataID = "amethyst_m_primarycolor",
        DataName = "Primary Color",
        DataDesc = "Primary color for the entire F4 menu.",
        DataType = "rgba",
        DataValues = { red = 51, alpha = 255, blue = 69, green = 43},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 240,
        DataID = "amethyst_m_secondarycolor",
        DataName = "Secondary Color",
        DataDesc = "Seconary color for the entire F4 menu.",
        DataType = "rgba",
        DataValues = { red = 68, alpha = 255, blue = 71, green = 114 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 250,
        DataID = "amethyst_m_primaryaccent_color",
        DataName = "Primary Accent Color",
        DataDesc = "Primary accent color (header panels).",
        DataType = "rgba",
        DataValues = { red = 10, alpha = 100, blue = 10, green = 10 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 260,
        DataID = "amethyst_m_secondaryaccent_color",
        DataName = "Secondary Accent Color",
        DataDesc = "Secondary accent color (content panels).",
        DataType = "rgba",
        DataValues = { red = 10, alpha = 160, blue = 10, green = 10 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 270,
        DataID = "amethyst_m_tertiaryaccent_color",
        DataName = "Tertiary Accent Color",
        DataDesc = "Tertiary accent color (right side section headers).",
        DataType = "rgba",
        DataValues = { red = 0, alpha = 20, blue = 114, green = 85 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 280,
        DataID = "amethyst_m_primarybordercolor",
        DataName = "Primary Border Color",
        DataDesc = "Primary border colors.",
        DataType = "rgba",
        DataValues = { red = 255, alpha = 3, blue = 255, green = 255},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 290,
        DataID = "amethyst_m_secondarybordercolor",
        DataName = "Secondary Border Color",
        DataDesc = "Secondary border colors (usually content and UI borders)",
        DataType = "rgba",
        DataValues = { red = 47, alpha = 255, blue = 94, green = 64},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 300,
        DataID = "amethyst_m_tcolor",
        DataName = "Text Color",
        DataDesc = "Main text color for the entire F4 menu.",
        DataType = "rgba",
        DataValues = { red = 255, alpha = 255, blue = 255, green = 255 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 310,
        DataID = "amethyst_m_iconcolor",
        DataName = "Icon Color",
        DataDesc = "Main color for all icons in F4 menu.",
        DataType = "rgba",
        DataValues = { red = 255, alpha = 255, blue = 255, green = 255 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 320,
        DataID = "amethyst_m_cmdblock_color",
        DataName = "Command Block Color",
        DataDesc = "Box color for command blocks (fourth tab).",
        DataType = "rgba",
        DataValues = { red = 124, alpha = 200, blue = 50, green = 51 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 321,
        DataID = "amethyst_m_primarybutton_color",
        DataName = "Primary Button Color",
        DataDesc = "Color for buttons throughout the F4 menu.",
        DataType = "rgba",
        DataValues = { red = 68, alpha = 255, blue = 71, green = 114 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 322,
        DataID = "amethyst_m_primarybutton_hcolor",
        DataName = "Primary Button Hover Color",
        DataDesc = "Color for buttons throughout the F4 menu.",
        DataType = "rgba",
        DataValues = { red = 68, alpha = 255, blue = 71, green = 180 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 323,
        DataID = "amethyst_m_primarybutton_ocolor",
        DataName = "Primary Button Outline Color",
        DataDesc = "Outline color for buttons.",
        DataType = "rgba",
        DataValues = { red = 124, alpha = 200, blue = 50, green = 51 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 324,
        DataID = "amethyst_m_secondarybutton_color",
        DataName = "Secondary Button Color",
        DataDesc = "Color for buttons throughout the F4 menu.",
        DataType = "rgba",
        DataValues = { red = 124, alpha = 200, blue = 50, green = 51 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 325,
        DataID = "amethyst_m_secondarybutton_hcolor",
        DataName = "Secondary Button Hover Color",
        DataDesc = "Color for buttons throughout the F4 menu.",
        DataType = "rgba",
        DataValues = { red = 124, alpha = 255, blue = 50, green = 51 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 326,
        DataID = "amethyst_m_secondarybutton_ocolor",
        DataName = "Secondary Button Outline Color",
        DataDesc = "Outline color for buttons.",
        DataType = "rgba",
        DataValues = { red = 124, alpha = 200, blue = 50, green = 51 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 327,
        DataID = "amethyst_m_button_tcolor",
        DataName = "Button Text Color",
        DataDesc = "Color of text within buttons.",
        DataType = "rgba",
        DataValues = { red = 124, alpha = 200, blue = 50, green = 51 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 330,
        DataID = "amethyst_padding_dashboard",
        DataName = "Padding",
        DataType = "padding",
    },
    {
        DataSort = 340,
        DataID = "amethyst_category_dashboard",
        DataName = "Dashboard",
        DataType = "category",
    },
    {
        DataSort = 350,
        DataID = "amethyst_desc_dashboard",
        DataName = "These settings are specifically for the Dashboard only.",
        DataType = "desc",
    },
    {
        DataSort = 355,
        DataIsVisible = true,
        DataID = "amethyst_m_dashboard_display_stats",
        DataName = "Display Statistics?",
        DataDesc = "Displays player statistics on Dashboard.",
        DataType = "checkbox",
        DataDefault = 1,
    },
    {
        DataSort = 356,
        DataIsVisible = true,
        DataID = "amethyst_m_dashboard_display_achievements",
        DataName = "Display Achievements?",
        DataDesc = "Displays the achievements panel on Dashboard.",
        DataType = "checkbox",
        DataDefault = 1,
    },
    {
        DataSort = 357,
        DataIsVisible = true,
        DataID = "amethyst_m_dashboard_display_agenda",
        DataName = "Display Agenda?",
        DataDesc = "Displays the agenda panel on Dashboard.",
        DataType = "checkbox",
        DataDefault = 1,
    },
    {
        DataSort = 358,
        DataIsVisible = true,
        DataID = "amethyst_m_dashboard_display_levelinfo",
        DataName = "Display XP/Level?",
        DataDesc = "Displays your XP/Level info on the Dashboard.",
        DataType = "checkbox",
        DataDefault = 1,
    },
    {
        DataSort = 360,
        DataID = "amethyst_m_dashboard_primary_color",
        DataName = "Dashboard Primary Color",
        DataDesc = "Main box color for items on the dashboard.",
        DataType = "rgba",
        DataValues = { red = 10, alpha = 200, blue = 10, green = 10},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 370,
        DataID = "amethyst_m_dashboard_secondary_color",
        DataName = "Dashboard Secondary Color",
        DataDesc = "Box header color for items on the dashboard.",
        DataType = "rgba",
        DataValues = { red = 68, alpha = 255, blue = 71, green = 114 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 380,
        DataID = "amethyst_m_dashboard_border_color",
        DataName = "Dashboard Border Color",
        DataDesc = "Border around item boxes on the dashboard.",
        DataType = "rgba",
        DataValues = { red = 255, alpha = 5, blue = 255, green = 255},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 390,
        DataID = "amethyst_padding_uicontrols",
        DataName = "Padding",
        DataType = "padding",
    },
    {
        DataSort = 400,
        DataID = "amethyst_category_uicontrols",
        DataName = "UI Controls",
        DataType = "category",
    },
    {
        DataSort = 410,
        DataID = "amethyst_ui_slider_lcolor",
        DataName = "Slider Line Color",
        DataDesc = "Color for the slider line UI.",
        DataType = "rgba",
        DataValues = { red = 255, alpha = 255, blue = 255, green = 255},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 420,
        DataID = "amethyst_ui_slider_gcolor",
        DataName = "Slider Grip Color",
        DataDesc = "Color for the slider grip UI.",
        DataType = "rgba",
        DataValues = { red = 255, alpha = 255, blue = 255, green = 255},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 430,
        DataID = "amethyst_ui_slider_tcolor",
        DataName = "Slider Text Color",
        DataDesc = "Slider text color for RGBA slider grip UI.",
        DataType = "rgba",
        DataValues = { red = 255, alpha = 255, blue = 255, green = 255},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 440,
        DataID = "amethyst_ui_rgba_r_gcolor",
        DataName = "RGBA Red Grip Color",
        DataDesc = "Red color for RGBA slider grip UI.",
        DataType = "rgba",
        DataValues = { red = 232, alpha = 255, blue = 53, green = 53},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 450,
        DataID = "amethyst_ui_rgba_g_gcolor",
        DataName = "RGBA Green Grip Color",
        DataDesc = "Green color for RGBA slider grip UI.",
        DataType = "rgba",
        DataValues = { red = 24, alpha = 255, blue = 24, green = 150},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 460,
        DataID = "amethyst_ui_rgba_b_gcolor",
        DataName = "RGBA Blue Grip Color",
        DataDesc = "Blue color for RGBA slider grip UI.",
        DataType = "rgba",
        DataValues = { red = 24, alpha = 255, blue = 150, green = 91},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 470,
        DataID = "amethyst_ui_rgba_a_gcolor",
        DataName = "RGBA Alpha Grip Color",
        DataDesc = "Alpha color for RGBA slider grip UI.",
        DataType = "rgba",
        DataValues = { red = 255, alpha = 255, blue = 255, green = 255},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 480,
        DataID = "amethyst_m_sbcolor",
        DataName = "Scrollbar Color",
        DataDesc = "Color of scrollbar.",
        DataType = "rgba",
        DataValues = { red = 200, alpha = 200, blue = 200, green = 200},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 490,
        DataID = "amethyst_m_chkbox_color",
        DataName = "Checkbox Color",
        DataDesc = "Color of checkbox.",
        DataType = "rgba",
        DataValues = { red = 51, alpha = 245, blue = 69, green = 43},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 500,
        DataID = "amethyst_m_chkbox_ocolor",
        DataName = "Checkbox Outline Color",
        DataDesc = "Color of outline for checkbox.",
        DataType = "rgba",
        DataValues = { red = 47, alpha = 255, blue = 94, green = 64},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 510,
        DataID = "amethyst_m_dropdown_color",
        DataName = "Dropdown Box Color",
        DataDesc = "Color of dropdown box.",
        DataType = "rgba",
        DataValues = { red = 51, alpha = 245, blue = 69, green = 43},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 520,
        DataID = "amethyst_m_dropdown_icolor",
        DataName = "Dropdown Box Inner Color",
        DataDesc = "Color of inner dropdown box.",
        DataType = "rgba",
        DataValues = { red = 51, alpha = 245, blue = 69, green = 43},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 530,
        DataID = "amethyst_m_dropdown_ocolor",
        DataName = "Dropdown Box Outline Color",
        DataDesc = "Color of outline for dropdown box.",
        DataType = "rgba",
        DataValues = { red = 51, alpha = 245, blue = 69, green = 43},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 535,
        DataID = "amethyst_m_textbox_ocolor",
        DataName = "Textbox Outline Color",
        DataDesc = "Color for outside of a textbox.",
        DataType = "rgba",
        DataValues = { red = 10, alpha = 100, blue = 10, green = 10 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 536,
        DataID = "amethyst_m_textbox_icolor",
        DataName = "Textbox Inside Color",
        DataDesc = "Color for Inside of a textbox.",
        DataType = "rgba",
        DataValues = { red = 10, alpha = 160, blue = 10, green = 10 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 537,
        DataID = "amethyst_m_textbox_tcolor",
        DataName = "Textbox Text Color",
        DataDesc = "Color for text of a textbox.",
        DataType = "rgba",
        DataValues = { red = 255, alpha = 255, blue = 255, green = 255},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 538,
        DataIsVisible = true,
        DataID = "amethyst_padding_notifications",
        DataName = "Padding",
        DataType = "padding",
    },
    {
        DataSort = 539,
        DataIsVisible = true,
        DataID = "amethyst_category_notifications",
        DataName = "Notifications",
        DataType = "category",
    },
    {
        DataSort = 540,
        DataIsVisible = true,
        DataID = "amethyst_desc_notifications",
        DataName = "This section allows you to colorize the notification system (the main sending page, and the notification that displays when a new one has been sent). Any settings not here are found elsewhere (IE: buttons).",
        DataType = "desc",
    },
    {
        DataSort = 541,
        DataIsVisible = true,
        DataID = "amethyst_n_primary_color",
        DataName = "Primary Color",
        DataDesc = "Color for text of a textbox.",
        DataType = "rgba",
        DataValues = { red = 51, alpha = 255, blue = 69, green = 43},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 542,
        DataIsVisible = true,
        DataID = "amethyst_n_secondary_color",
        DataName = "Secondary Color",
        DataDesc = "Color for text of a textbox.",
        DataType = "rgba",
        DataValues = { red = 40, alpha = 255, blue = 40, green = 40},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 543,
        DataIsVisible = true,
        DataID = "amethyst_n_outline_color",
        DataName = "Outline Color",
        DataDesc = "Color for text of a textbox.",
        DataType = "rgba",
        DataValues = { red = 255, alpha = 3, blue = 255, green = 255},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 544,
        DataIsVisible = true,
        DataID = "amethyst_n_text_color",
        DataName = "Text Color",
        DataDesc = "Color for text of a textbox.",
        DataType = "rgba",
        DataValues = { red = 255, alpha = 255, blue = 255, green = 255},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 545,
        DataID = "amethyst_padding_stats",
        DataName = "Padding",
        DataType = "padding",
    },
    {
        DataSort = 550,
        DataID = "amethyst_category_stats",
        DataName = "Player Stats",
        DataType = "category",
    },
    {
        DataSort = 560,
        DataID = "amethyst_m_stabs_text_statsenabled",
        DataName = "Display Stats Text?",
        DataDesc = "Displays the actual text value of each stat.",
        DataType = "checkbox",
        DataDefault = 1,
    },
    {
        DataSort = 570,
        DataID = "amethyst_m_stabs_text_type",
        DataName = "Text Or Icon Display",
        DataDesc = "How do you want to display your info in the side tabs?",
        DataType = "dropdown",
        DataDefault = "icons",
        DataValues = {"icons", "text"},
    },
    {
        DataSort = 580,
        DataID = "amethyst_m_stats_hcolor",
        DataName = "Health Progress Color",
        DataDesc = "Color of health progress bar when filling up.",
        DataType = "rgba",
        DataValues = { red = 100, alpha = 165, blue = 75, green = 153},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 590,
        DataID = "amethyst_m_stats_acolor",
        DataName = "Armor Progress Color",
        DataDesc = "Color of armor progress bar when filling up.",
        DataType = "rgba",
        DataValues = { red = 43, alpha = 165, blue = 216, green = 137},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 600,
        DataID = "amethyst_m_stats_scolor",
        DataName = "Stamina Progress Color",
        DataDesc = "Color of stamina progress bar when filling up.",
        DataType = "rgba",
        DataValues = { red = 170, alpha = 165, blue = 95, green = 85},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 610,
        DataID = "amethyst_m_stats_hungercolor",
        DataName = "Hunger Progress Color",
        DataDesc = "Color of hunger progress bar when filling up.",
        DataType = "rgba",
        DataValues = { red = 100, alpha = 165, blue = 136, green = 90},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 620,
        DataID = "amethyst_m_stats_xpcolor",
        DataName = "XP Progress Color",
        DataDesc = "Color of xp progress bar when filling up.",
        DataType = "rgba",
        DataValues = { red = 165, alpha = 165, blue = 195, green = 105},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 630,
        DataID = "amethyst_padding_avatars",
        DataName = "Padding",
        DataType = "padding",
    },
    {
        DataSort = 640,
        DataID = "amethyst_category_avatars",
        DataName = "Avatars",
        DataType = "category",
    },
    {
        DataSort = 650,
        DataID = "amethyst_desc_avatars",
        DataName = "This area allows you to control how your avatar appears within the F4 menu. You can choose between either your standard steam avatar, or a player model render with a few customization settings. ",
        DataType = "desc",
    },
    {
        DataSort = 660,
        DataID = "amethyst_avatar_pmodel_enabled",
        DataName = "Player Model Enabled",
        DataDesc = "If enabled, player model avatar will show. Disabled will show steam avatar instead.",
        DataType = "checkbox",
        DataDefault = 1,
    },
    {
        DataSort = 670,
        DataID = "amethyst_avatar_fov",
        DataName = "Field of View",
        DataDesc = "Player Model Enabled Only: Field of view",
        DataType = "slider",
        DataDefault = 18,
        DataValues = {  },
        DataMin = 0,
        DataMax = 25,
    },
    {
        DataSort = 680,
        DataID = "amethyst_avatar_campos_x",
        DataName = "CamPOS X",
        DataDesc = "Player Model Enabled Only: X Position for Camera",
        DataType = "slider",
        DataDefault = 85,
        DataValues = {  },
        DataMin = 50,
        DataMax = 100,
    },
    {
        DataSort = 690,
        DataID = "amethyst_avatar_campos_y",
        DataName = "CamPOS Y",
        DataDesc = "Player Model Enabled Only: Y Position for Camera",
        DataType = "slider",
        DataDefault = -11,
        DataValues = {  },
        DataMin = -25,
        DataMax = 25,
    },
    {
        DataSort = 700,
        DataID = "amethyst_avatar_campos_z",
        DataName = "CamPOS Z",
        DataDesc = "Player Model Enabled Only: Z Position for Camera",
        DataType = "slider",
        DataDefault = 65,
        DataValues = {  },
        DataMin = 50,
        DataMax = 100,
    },
    {
        DataSort = 710,
        DataID = "amethyst_avatar_lookat_x",
        DataName = "LookAt X",
        DataDesc = "Player Model Enabled Only: X LookAt Position",
        DataType = "slider",
        DataDefault = -2,
        DataValues = {  },
        DataMin = -15,
        DataMax = 15,
    },
    {
        DataSort = 720,
        DataID = "amethyst_avatar_lookat_y",
        DataName = "LookAt Y",
        DataDesc = "Player Model Enabled Only: Y LookAt Position",
        DataType = "slider",
        DataDefault = 1,
        DataValues = {  },
        DataMin = -15,
        DataMax = 15,
    },
    {
        DataSort = 730,
        DataID = "amethyst_avatar_lookat_z",
        DataName = "LookAt Z",
        DataDesc = "Player Model Enabled Only: Z LookAt Position",
        DataType = "slider",
        DataDefault = 62,
        DataValues = {  },
        DataMin = 50,
        DataMax = 100,
    },
    {
        DataSort = 740,
        DataID = "amethyst_m_avatar_ccolor",
        DataName = "Circle Color",
        DataDesc = "Avatar Circle Color (displays around avatar).",
        DataType = "rgba",
        DataValues = { red = 110, alpha = 210, blue = 138, green = 98 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 750,
        DataID = "amethyst_padding_sidetabs",
        DataName = "Padding",
        DataType = "padding",
    },
    {
        DataSort = 760,
        DataID = "amethyst_category_sidetabs",
        DataName = "Side Tabs",
        DataType = "category",
    },
    {
        DataSort = 770,
        DataID = "amethyst_desc_sidetabs",
        DataName = "These settings modify the sidetabs to the left -- which are how you navigate between the different sections of the F4 menu. They will appear as four (4) dots to the top left below the clock. (Not available in Compact Mode)",
        DataType = "desc",
    },
    {
        DataSort = 780,
        DataID = "amethyst_m_stabs_objheight",
        DataName = "Button Height",
        DataDesc = "The height of each button (jobs, ammo, website, steam, etc).",
        DataType = "slider",
        DataDefault = 45,
        DataValues = {  },
        DataMin = 20,
        DataMax = 60,
    },
    {
        DataSort = 790,
        DataID = "amethyst_m_stabs_acolor",
        DataName = "Active Color",
        DataDesc = "Color for an active side tab circle.",
        DataType = "rgba",
        DataValues = { red = 54, alpha = 255, blue = 75, green = 158},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 800,
        DataID = "amethyst_m_stabs_outline_acolor",
        DataName = "Outline Active Color",
        DataDesc = "Color for an outline active side tab circle.",
        DataType = "rgba",
        DataValues = { red = 29, alpha = 255, blue = 40, green = 87},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 810,
        DataID = "amethyst_m_stabs_icolor",
        DataName = "Inactive Color",
        DataDesc = "Color for an inactive side tab circle.",
        DataType = "rgba",
        DataValues = { red = 97, alpha = 230, blue = 105, green = 85},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 820,
        DataID = "amethyst_m_stabs_outline_icolor",
        DataName = "Outline Inactive Color",
        DataDesc = "Color for an outline inactive side tab circle.",
        DataType = "rgba",
        DataValues = { red = 97, alpha = 230, blue = 105, green = 85},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 830,
        DataID = "amethyst_m_stabs_button_hcolor",
        DataName = "Button Hover Color",
        DataDesc = "Color for the sidebar that displays when hovering over a button.",
        DataType = "rgba",
        DataValues = { red = 255, alpha = 100, blue = 255, green = 255},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 840,
        DataID = "amethyst_m_stabs_button_scolor",
        DataName = "Button Selected Color",
        DataDesc = "Color for the sidebar that displays when button is selected.",
        DataType = "rgba",
        DataValues = { red = 255, alpha = 220, blue = 255, green = 255},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 850,
        DataID = "amethyst_padding_globaltabs",
        DataName = "Padding",
        DataType = "padding",
    },
    {
        DataSort = 860,
        DataID = "amethyst_category_globaltabs",
        DataName = "Global Tabs",
        DataType = "category",
    },
    {
        DataSort = 870,
        DataID = "amethyst_desc_globaltabs",
        DataName = "These settings modify the style for jobs, shipments, ammo, entities, etc. Changing the setting for each item, changes all categories properties (unless the setting states otherwise that it's only for one particular group).",
        DataType = "desc",
    },
    {
        DataSort = 880,
        DataID = "amethyst_g_useicons_enabled",
        DataName = "Use Job Icons",
        DataDesc = "Display job icons instead of models.",
        DataType = "checkbox",
        DataDefault = 0,
    },
    {
        DataSort = 890,
        DataID = "amethyst_g_primarycolor",
        DataName = "Primary Color",
        DataDesc = "Primary background color for all items in each section.",
        DataType = "rgba",
        DataValues = { red = 78, alpha = 120, blue = 78, green = 55},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 900,
        DataID = "amethyst_g_secondarycolor",
        DataName = "Secondary Color",
        DataDesc = "Secondary color for all items in each section (right rounded boxes).",
        DataType = "rgba",
        DataValues = { red = 68, alpha = 255, blue = 71, green = 114 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 910,
        DataID = "amethyst_g_bordercolor",
        DataName = "Border Color",
        DataDesc = "Border color for all items in each section.",
        DataType = "rgba",
        DataValues = { red = 78, alpha = 200, blue = 78, green = 55},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 920,
        DataID = "amethyst_g_box_tcolor",
        DataName = "Item Text Color",
        DataDesc = "Text color for all items in each section.",
        DataType = "rgba",
        DataValues = { red = 255, alpha = 255, blue = 255, green = 255},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 930,
        DataID = "amethyst_g_desc_ccolor",
        DataName = "Preview Circle Color",
        DataDesc = "Item preview circle color for all items in each section.",
        DataType = "rgba",
        DataValues = { red = 110, alpha = 210, blue = 138, green = 98 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 940,
        DataID = "amethyst_g_desc_tcolor",
        DataName = "Preview Text Color",
        DataDesc = "Preview text color for all items in each section.",
        DataType = "rgba",
        DataValues = { red = 255, alpha = 255, blue = 255, green = 255},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 950,
        DataID = "amethyst_g_button_bcolor",
        DataName = "Item Button Color",
        DataDesc = "Item action button color for all items in each section (to purchase, become job, etc).",
        DataType = "rgba",
        DataValues = { red = 68, alpha = 255, blue = 71, green = 114 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 960,
        DataID = "amethyst_g_altbutton_bcolor",
        DataName = "Item Alt Button Color",
        DataDesc = "Alternative item action button color for all items in each section (vote for job, cannot buy, etc).",
        DataType = "rgba",
        DataValues = { red = 0, alpha = 255, blue = 140, green = 90 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 970,
        DataID = "amethyst_g_unavailablebutton_bcolor",
        DataName = "Item Unavailable Button Color",
        DataDesc = "Item button color for things that cannot be purchased for whatever reason.",
        DataType = "rgba",
        DataValues = { red = 170, alpha = 165, blue = 95, green = 85},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 980,
        DataID = "amethyst_g_icon_acolor",
        DataName = "Active Icon Color",
        DataDesc = "Color for icon (checkmark by default) of job that you are currently set as.",
        DataType = "rgba",
        DataValues = { red = 68, alpha = 255, blue = 71, green = 114 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 990,
        DataID = "amethyst_g_alticon_acolor",
        DataName = "Alt Icon Color",
        DataDesc = "Color for icon (gavel by default) of job that requires voting.",
        DataType = "rgba",
        DataValues = { red = 0, alpha = 255, blue = 140, green = 90 },
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 1000,
        DataID = "amethyst_g_cat_tcolor",
        DataName = "Category Text Color",
        DataDesc = "Text color for all category names.",
        DataType = "rgba",
        DataValues = { red = 255, alpha = 255, blue = 255, green = 255},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 1010,
        DataID = "amethyst_g_cat_norm_icolor",
        DataName = "Category Icon Color",
        DataDesc = "Icon color for a category that is expanded.",
        DataType = "rgba",
        DataValues = { red = 255, alpha = 255, blue = 255, green = 255},
        DataMin = 0,
        DataMax = 255,
    },
    {
        DataSort = 1020,
        DataID = "amethyst_g_cat_collapse_icolor",
        DataName = "Category Icon Collapse Color",
        DataDesc = "Icon color for a category that is collapsed.",
        DataType = "rgba",
        DataValues = { red = 255, alpha = 255, blue = 255, green = 255},
        DataMin = 0,
        DataMax = 255,
    },
}
